#!/bin/bash

# INPUTS FROM launchCP2Ks
INPFILE=$1                                                            #input file
NPROCS=$2                                                             #number of CPUs
LOGFILE=$PBS_O_WORKDIR/$1_${PBS_JOBID}.log
OUTFILE=$1.out

#PBS -V

#ENVRINMENT VARIABLE AND MODULE LOAD
module purge
module load imkl/2017.1.132-iimpi-2017a
module load MPICH/3.2-GCC-5.3.1-snapshot-20160419-2.25

export OMP_NUM_THREADS=1
export SCRDIR=/scratch/work/user/$USER/cp2k_${INPFILE}_${PBS_JOBID}    # SCRATCH DIR WHERE TO RUN JOB
export CP2KEXE=/home/chalabaj/install/cp2k-5.1/exe/local/cp2k.popt   # MPI PARALLEL VERSION { possible to use other ssmp etc but not regtestes
export CP2K_DATA_DIR=/home/chalabaj/install/cp2k-5.1/data            # Where to find CP2K files such as basis set, PP etc
#--------------------------------------------------------

#PREPARE LOG FILE
echo  ${PBS_JOBID}     > ${LOGFILE}
echo  ${USER}         >> ${LOGFILE}
echo  ${SCRDIR}      >>  ${LOGFILE}
echo  $PBS_O_WORKDIR  >>  ${LOGFILE}
echo "start"          >> ${LOGFILE}
#--------------------------------------------------------

#PREPAREDIR AND RUN CALC
mkdir $SCRDIR

cp $PBS_O_WORKDIR/* $SCRDIR/.
cd $SCRDIR

mpiexec -np $NPROCS $CP2KEXE  -i $INPFILE > $OUTFILE 
echo "Job terminated normally."          >> ${LOGFILE}
#--------------------------------------------------------

#COPY CLEAN EXIT
cd ../
cp -pr $SCRDIR ${PBS_O_WORKDIR}/.
#cp $SCRDIR/$OUTFILE ${PBS_O_WORKDIR}/.
rm -rf $SCRDIR
#--------------------------------------------------------

#EXIT
module purge
exit
