#!/bin/bash

function PrintHelp {
   echo " "
   echo "USAGE: 'launchCP2Ks inputfile nproc que walltime=hh:mm:ss patched/unpatched   (patched = Frank MO SCF patch)' "
   echo "que = qexp (max 1 hour); qprod (max 48 hours), qlong (max 144 hours)"
   exit 1
}

if [[ $# -lt "5" ]]; then
   echo "Not enough parameters."
   PrintHelp
fi

#INPUT FILE
input=$1
name=`echo "$input" | cut -d'.' -f1`     #namefile without extenson

if [[ ! -e "$input" ]];then
   echo "File $input does not exist. Exiting."
   PrintHelp
fi

nproc=$2
if [ "`echo ${nproc} | grep '^[0-9]*$'`" != ${nproc} ]; then
    echo "Error: number_of_cpus parameter is not a number!"
    PrintHelp
fi

#which queue  #qexp qprod
queue=$3
if [ "$queue" != "qprod" ] && [ "$queue" != "qexp" ] && [ "$queue" != "qlong" ] ; then
echo "error: unknown que: $queue; use qprod, glong or qexp for testing"
PrintHelp
fi

#mpiprocs=4:
walltime=$4
PATCHED=$5

if [ "$PATCHED" != "unpatched" ] && [ "$PATCHED" != "patched" ] ; then  
echo "error: unknown version: $PATCHED; use patched or unpatched"
PrintHelp
fi

cat > r.$name << EOF
#!/bin/bash

#PBS -q $queue
#PBS -N $name.out
#PBS -l select=1:ncpus=24:mpiprocs=24:mem=96gb
#PBS -l walltime=$walltime
#PBS -A OPEN-10-48

CP2Ks $input $nproc $PATCHED
EOF

echo "Submitting CP2K job for single node parallel execution in ${queue} que with ${nproc} processes."

qsub r.$name


