#!/bin/bash

#PBS -V
# Molpro 2012 SGE submission script (single- and nulti-processor version)

INPFILE=$1
LOGFILE=$1.log
OUTFILE=$1.out
nproc=${NSLOTS}

scratch=/scratch/work/user/$USER/
export SCRATCH=${scratch}/MOLPRO-${PBS_JOBID}
export INTGDIR=${scratch}/MOLPRO-${PBS_JOBID}
export WORKDIR=$PBS_O_WORKDIR
mkdir -p $SCRATCH

export MOLPRO_OPTIONS="--nobackup --no-xml-output -o${OUTFILE} -d${SCRATCH} -I${INTGDIR} -W${WORKDIR}"
export MOLPROEXE=/home/chalabaj/prog/molpro/molprop_2012/bin/molpro
export OMP_NUM_THREADS=1
export MPIRUN=/home/chalabaj/prog/opempi/1.10.4/bin/mpirun
/bin/uname -a >${LOGFILE}
/bin/date >>${LOGFILE}
/bin/echo >>${LOGFILE}
echo  ${PBS_JOBID}    > ${LOGFILE}
echo  ${USER}         >> ${LOGFILE}
echo  ${SCRDIR}       >>  ${LOGFILE}
echo  $PBS_O_WORKDIR  >>  ${LOGFILE}


cp $WORKDIR/$INPFILE $SCRATCH/.
cd $SCRATCH

#$MOLPROEXE <${INPFILE} >> ${LOGFILE}
$MOLPROEXE <${INPFILE} >> ${LOGFILE}
#   /usr/bin/time -a -o ${LOGFILE} $MOLPROEXE <${INPFILE} >>${LOGFILE}

cp $SCRATCH/* $WORKDIR/.
rm -rf $SCRATCH

