#!/bin/bash

#PBS -V
# Molpro 2012 SGE submission script (single- and nulti-processor version)

INPFILE=$1
LOGFILE=$1.log
OUTFILE=$1.out
nproc=$2

scratch=/scratch/work/user/$USER/
export SCRATCH=${scratch}/MOLPRO-${PBS_JOBID}
export INTGDIR=${scratch}/MOLPRO-${PBS_JOBID}
export WORKDIR=${PBS_O_WORKDIR}
mkdir -p $SCRATCH

export MOLPRO_OPTIONS="--nobackup --no-xml-output -o${OUTFILE} -d${SCRATCH} -I${INTGDIR} -W${WORKDIR} -m8M"
export MOLPROEXE=/home/chalabaj/prog/molpro/molprop_2012/bin/molpro
#export MOLPROEXE=/home/chalabaj/prog/molpro/molprop_2015_1_linux_x86_64_i8/bin/molpro
export OMP_NUM_THREADS=12
export MPIRUN=/home/chalabaj/prog/opempi/1.10.4/bin/mpirun

#cp $PBS_O_WORKDIR/$INPFILE $SCRATCH/.
cd $WORKDIR 
echo  ${PBS_JOBID}    > ${LOGFILE}
echo  ${USER}         >> ${LOGFILE}
echo  ${SCRATCH}       >>  ${LOGFILE}
echo  $PBS_O_WORKDIR  >>  ${LOGFILE}


$MPIRUN -np $nproc --hostfile $PBS_NODEFILE $MOLPROEXE < $INPFILE >> ${LOGFILE} 

#   /usr/bin/time -a -o ${LOGFILE} $MOLPROEXE <${INPFILE} >>${LOGFILE}

#cp  $SCRATCH/* ${PBS_O_WORKDIR}/.
#rm -rf $SCRATCH

